# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Seup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - uses: actions/checkout@v1

      - name: Setup git
        run: |
          git config --local user.email "alex@dytry.ch"
          git config --local user.name "alex"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
          git checkout ${GITHUB_REF##refs/heads/}
      - name: Install dependencies
        run: yarn --non-interactive --frozen-lockfile
      - name: Test
        run: yarn run test
      - name: Build
        run: yarn build
      - name: Commit & push changes
        run: |
          mv dist ../dist-tmp
          git checkout gh-pages
          git ls-files | xargs git rm
          rm -rf node_modules .cache .parcel-cache
          cp -r ../dist-tmp/* ./
          git add -A
          git commit --allow-empty --no-verify -m "[automated] publish" -m "This commit was generated by .github/workflows/publish.yml on $(date)."
          git push
